<a href="https://colab.research.google.com/github/Hyon2-park/test/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%80%ED%8A%B8%EC%BA%A0%ED%94%84_3%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

ph=pd.read_csv('/content/purchase.csv')
ph

   order_id customer_id product  qty  amount  order_date
0      1001         C01      우유  2.0  4000.0  20240701.0
1      1002         C02       빵  NaN  2500.0  20240701.0
2      1003         C01      계란  1.0     NaN  20240702.0
3      1004         C03      라면  3.0  3000.0  20240702.0
4      1005         C02      우유  NaN  4000.0  20240703.0
5      1006         C04      과자  2.0  1800.0         NaN
6      1007         C03       빵  1.0  2500.0  20240703.0
7      1008         C01      라면  2.0     NaN  20240704.0
8      1009         C05      우유  1.0  2000.0  20240704.0
9      1010         C02      과자  NaN     NaN         NaN

In [4]:
ph.isnull().sum()

order_id       0
customer_id    0
product        0
qty            3
amount         3
order_date     2
dtype: int64

In [5]:
ph.shape

(10, 6)

In [6]:
ph.columns

Index(['order_id', 'customer_id', 'product', 'qty', 'amount', 'order_date'], dtype='object')

In [7]:
ph.head()

   order_id customer_id product  qty  amount  order_date
0      1001         C01      우유  2.0  4000.0  20240701.0
1      1002         C02       빵  NaN  2500.0  20240701.0
2      1003         C01      계란  1.0     NaN  20240702.0
3      1004         C03      라면  3.0  3000.0  20240702.0
4      1005         C02      우유  NaN  4000.0  20240703.0

In [9]:
ph.dtypes

order_id         int64
customer_id     object
product         object
qty            float64
amount         float64
order_date     float64
dtype: object

In [11]:
ph.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     10 non-null     int64
 1   customer_id  10 non-null     object
 2   product      10 non-null     object
 3   qty          7 non-null      float64
 4   amount       7 non-null      float64
 5   order_date   8 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

# iloc, 결측치 처리

In [13]:
df = pd.read_csv('/content/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
df[['Age','Name','Sex']]

      Age                                               Name     Sex
0    22.0                            Braund, Mr. Owen Harris    male
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2    26.0                             Heikkinen, Miss. Laina  female
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4    35.0                           Allen, Mr. William Henry    male
..    ...                                                ...     ...
886  27.0                              Montvila, Rev. Juozas    male
887  19.0                       Graham, Miss. Margaret Edith  female
888   NaN           Johnston, Miss. Catherine Helen "Carrie"  female
889  26.0                              Behr, Mr. Karl Howell    male
890  32.0                                Dooley, Mr. Patrick    male

[891 rows x 3 columns]

In [16]:
df.loc[df['Age']>=20,['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
884                             Sutehall, Mr. Henry Jr  25.0
885               Rice, Mrs. William (Margaret Norton)  39.0
886                              Montvila, Rev. Juozas  27.0
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[550 rows x 2 columns]

In [17]:
#인덱스 라벨이 0~10까지의 이름과 나이 출력
df.loc[0:10,['Name','Age']]

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0

In [20]:
gb.groupby(level='점포ID')['구매수량'].max()

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [25]:
#0~4번 행 가져오기
df.iloc[0:5]
#2~6행, 0~2열 출력
df.iloc[2:7,0:3]

   PassengerId  Survived  Pclass
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1

In [26]:
#성별, 객실 등급 별 fare의 평균 값 계산
df.groupby(['Sex','Pclass'])['Fare'].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [29]:
df.notna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,True,True,True,True,True,True,True,True,True,True,False,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,False,True
887,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,True,True,False,True,True,True,True,False,True
889,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,False,True

In [30]:
df['Age'].isna().sum()

np.int64(177)

In [31]:
# mean() 은 결측치는 자동으로 제외하고 평균을 계산한다.
df['Age'].mean()

np.float64(29.69911764705882)

In [33]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [34]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [35]:
df['Cabin']=df['Cabin'].fillna('N')
df['Cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
886       N
887     B42
888       N
889    C148
890       N
Name: Cabin, Length: 891, dtype: object

# 파생 변수 생성
1. 가족 수를 생성하기 위해 형제자매 + 부모 + 1(본인) 을 계산해 새 컬럼 생성

# 그룹별 수
value_counts()

In [36]:
#family  파생변수 생성
df['family']=df['SibSp']+df['Parch'] +1

In [37]:
#value_count : 그룹별 수
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

# 데이터 EDA

In [ ]:
# 가장 많이 구매 된 제품명 & 대분류
# 거래시간대 별 구매 상품
# 점포별 팔린 제품의 차이가 있을 것이다. (T검정, 카이검정)
# 점포와 연월별 판매량 추이
# 장바구니 분석

In [2]:
import pandas as pd
df1=pd.read_csv('/content/구매내역정보.csv',encoding='cp949')
df1

            ID   거래식별ID 점포ID      거래일자  거래시간대 상품대분류명    상품중분류명  구매수량   구매금액
0      B000001  Z000403    B  20140704     21     청과  감귤수박국산기타     1  12900
1      B000001  Z000677    B  20140707     14     낙농        우유     2   1700
2      B000001  Z000677    B  20140707     14    면과자         빵     1   1800
3      B000001  Z001259    B  20140714     17    음주류        주류     1  11200
4      B000001  Z001364    B  20140715     18     낙농       발효유     1   2200
...        ...      ...  ...       ...    ...    ...       ...   ...    ...
55828  B001500  Z016472    A  20140830     16     야채       두채류     1   2290
55829  B001500  Z019236    A  20140920     20    음주류        주류     1   1300
55830  B001500  Z019741    A  20140923     13     낙농       발효유     1   1700
55831  B001500  Z020273    A  20140926     20     야채       계란류     1   4990
55832  B001500  Z020641    A  20140930     14     낙농        우유     1   2600

[55833 rows x 9 columns]

In [28]:
gb=df1.groupby(['점포ID','상품중분류명'])['구매수량'].sum()
# 각 점포별로 구매수량이 가장 높은 상품중분류명의 인덱스(점포ID, 상품중분류명)를 찾습니다.
best_seller_indices = gb.groupby(level='점포ID').idxmax() # 최대값의 인덱스 반환

# 해당 인덱스를 사용하여 gb Series에서 가장 많이 팔린 제품의 정보(제품명, 구매수량)를 가져옵니다.
best_sellers_info = gb.loc[best_seller_indices]

display(best_sellers_info) #더 보기 좋게 출력하기 위해 사용

점포ID  상품중분류명
A     음료        9151
B     아이스크림     4808
Name: 구매수량, dtype: int64

In [22]:
# 1. 데이터 구조 확인하기
df1.shape

(55833, 9)

In [23]:
df1.columns

Index(['ID', '거래식별ID', '점포ID', '거래일자', '거래시간대', '상품대분류명', '상품중분류명', '구매수량',
       '구매금액'],
      dtype='object')

In [24]:
df1.head()

        ID   거래식별ID 점포ID      거래일자  거래시간대 상품대분류명    상품중분류명  구매수량   구매금액
0  B000001  Z000403    B  20140704     21     청과  감귤수박국산기타     1  12900
1  B000001  Z000677    B  20140707     14     낙농        우유     2   1700
2  B000001  Z000677    B  20140707     14    면과자         빵     1   1800
3  B000001  Z001259    B  20140714     17    음주류        주류     1  11200
4  B000001  Z001364    B  20140715     18     낙농       발효유     1   2200

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55833 entries, 0 to 55832
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      55833 non-null  object
 1   거래식별ID  55833 non-null  object
 2   점포ID    55833 non-null  object
 3   거래일자    55833 non-null  int64
 4   거래시간대   55833 non-null  int64
 5   상품대분류명  55833 non-null  object
 6   상품중분류명  55833 non-null  object
 7   구매수량    55833 non-null  int64
 8   구매금액    55833 non-null  int64
dtypes: int64(4), object(5)
memory usage: 3.8+ MB

In [27]:
df1.describe()

               거래일자         거래시간대          구매수량           구매금액
count  5.583300e+04  55833.000000  55833.000000   55833.000000
mean   2.014081e+07     17.074544      1.623663    4644.907259
std    8.187651e+01      3.308774      2.010506    5402.976512
min    2.014070e+07     10.000000      1.000000     100.000000
25%    2.014072e+07     15.000000      1.000000    1990.000000
50%    2.014082e+07     18.000000      1.000000    3300.000000
75%    2.014091e+07     20.000000      2.000000    5800.000000
max    2.014093e+07     22.000000    100.000000  289000.000000

In [29]:
#2. 결측치 확인
df1.isnull().sum()

ID        0
거래식별ID    0
점포ID      0
거래일자      0
거래시간대     0
상품대분류명    0
상품중분류명    0
구매수량      0
구매금액      0
dtype: int64